# Generated by Django 5.0.1 on 2024-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeApp', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
